
import React from 'react';
import { ArrowLeftIcon } from './Icons';

interface PolicyProps {
  onBack: () => void;
}

const PolicyContainer: React.FC<{ title: string; onBack: () => void; children: React.ReactNode }> = ({ title, onBack, children }) => (
  <div className="pt-32 pb-24 px-6 max-w-4xl mx-auto animate-fade-in font-['Nunito']">
    <button onClick={onBack} className="flex items-center gap-2 text-sm font-black text-slate-400 hover:text-slate-900 mb-8 transition-colors uppercase tracking-widest">
      <ArrowLeftIcon className="w-4 h-4" /> Back
    </button>
    <h1 className="text-4xl md:text-5xl font-black text-slate-900 mb-10 tracking-tight">{title}</h1>
    <div className="prose prose-slate prose-lg max-w-none font-medium text-slate-600 leading-relaxed space-y-6">
      {children}
    </div>
  </div>
);

export const PrivacyPolicy: React.FC<PolicyProps> = ({ onBack }) => (
  <PolicyContainer title="Privacy Policy" onBack={onBack}>
    <p>Last Updated: {new Date().toLocaleDateString()}</p>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">1. Introduction</h2>
      <p>At ChildTale, we are committed to protecting your privacy. This policy explains how we collect, use, and safeguard your data in compliance with GDPR and CCPA regulations.</p>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">2. Data We Collect</h2>
      <ul className="list-disc pl-6 space-y-2">
        <li><strong>Account Information:</strong> Email address used for authentication via Supabase.</li>
        <li><strong>User Inputs:</strong> Names of children, ages, and story prompts provided to generate books.</li>
        <li><strong>Generated Content:</strong> The text and images created by our magic engine based on your prompts.</li>
        <li><strong>Usage Data:</strong> Basic analytics and cookies to ensure the application functions correctly.</li>
      </ul>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">3. How We Use Your Data</h2>
      <p>We use your data solely to provide the ChildTale service, specifically to generate personalized coloring books. We do not sell your personal data to third parties.</p>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">4. GDPR Rights</h2>
      <p>If you are in the EU, you have the right to access, rectify, or delete your personal data. You may also object to processing or request data portability. Contact us at <strong>childtale4@gmail.com</strong> to exercise these rights.</p>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">5. CCPA Compliance</h2>
      <p>California residents have the right to know what personal information is collected, to delete it, and to opt-out of the "sale" of their information. ChildTale does not sell personal information.</p>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">6. Security</h2>
      <p>We utilize industry-standard security measures provided by Supabase and Google Cloud to protect your data.</p>
    </section>
  </PolicyContainer>
);

export const TermsOfService: React.FC<PolicyProps> = ({ onBack }) => (
  <PolicyContainer title="Terms of Service" onBack={onBack}>
    <p>Last Updated: {new Date().toLocaleDateString()}</p>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">1. Acceptance of Terms</h2>
      <p>By using ChildTale, you agree to these terms. If you do not agree, please do not use the service.</p>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">2. Usage Rules</h2>
      <p>Users must not generate content that is illegal, harmful, threatening, abusive, or otherwise objectionable. ChildTale is intended for family-friendly use. Any violation may result in account termination.</p>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">3. Intellectual Property</h2>
      <p><strong>Hybrid Creation & Ownership:</strong> ChildTale uses a "Hybrid Creation" model. While the raw black-and-white outlines are generated by our Magic Engine (powered by Google's Gemini technology) and are subject to its license terms, the <strong>final colored artwork</strong> created by you in the Magic Studio represents your unique creative contribution ("Hybrid Authorship").</p>
      <p className="mt-4">You are granted a personal, non-commercial license to use the generated storybooks. You own your specific color selections and artistic modifications.</p>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">4. Payments and Refunds</h2>
      <p>Purchases of digital and physical books are final. Given the personalized nature of our products, we generally do not offer refunds unless there is a significant manufacturing defect in physical products.</p>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">5. Contact</h2>
      <p>For any questions regarding these terms, please contact <strong>childtale4@gmail.com</strong>.</p>
    </section>
  </PolicyContainer>
);

export const CookiePolicy: React.FC<PolicyProps> = ({ onBack }) => (
  <PolicyContainer title="Cookie Policy" onBack={onBack}>
    <p>Last Updated: {new Date().toLocaleDateString()}</p>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">1. What are Cookies?</h2>
      <p>Cookies are small text files stored on your device that help our website function and improve your user experience.</p>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">2. How We Use Cookies</h2>
      <ul className="list-disc pl-6 space-y-2">
        <li><strong>Essential Cookies:</strong> Required for logging in and account security (handled by Supabase).</li>
        <li><strong>Functional Cookies:</strong> Remember your preferences and temporary state within the app.</li>
        <li><strong>Analytical Cookies:</strong> Help us understand how the app is being used to improve our service.</li>
      </ul>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">3. Managing Cookies</h2>
      <p>You can control and manage cookies through your browser settings. However, disabling essential cookies will prevent you from using the ChildTale service.</p>
    </section>
    <section>
      <h2 className="text-2xl font-black text-slate-900 mt-8 mb-4">4. GDPR/CCPA Consent</h2>
      <p>By using our site, you consent to our use of cookies in accordance with this policy. We provide a clear consent banner for all new visitors.</p>
    </section>
  </PolicyContainer>
);
