
export const SUPPORTED_COUNTRIES = [
    { code: "AF", name: "🇦🇫 Afghanistan" },
    { code: "AL", name: "🇦🇱 Albania" },
    { code: "DZ", name: "🇩🇿 Algeria" },
    { code: "AS", name: "🇦🇸 American Samoa" },
    { code: "AD", name: "🇦🇩 Andorra" },
    { code: "AO", name: "🇦🇴 Angola" },
    { code: "AI", name: "🇦🇮 Anguilla" },
    { code: "AG", name: "🇦🇬 Antigua and Barbuda" },
    { code: "AR", name: "🇦🇷 Argentina" },
    { code: "AM", name: "🇦🇲 Armenia" },
    { code: "AW", name: "🇦🇼 Aruba" },
    { code: "AU", name: "🇦🇺 Australia" },
    { code: "AT", name: "🇦🇹 Austria" },
    { code: "AZ", name: "🇦🇿 Azerbaijan" },
    { code: "BS", name: "🇧🇸 Bahamas" },
    { code: "BH", name: "🇧🇭 Bahrain" },
    { code: "BD", name: "🇧🇩 Bangladesh" },
    { code: "BB", name: "🇧🇧 Barbados" },
    { code: "BE", name: "🇧🇪 Belgium" },
    { code: "BZ", name: "🇧🇿 Belize" },
    { code: "BJ", name: "🇧🇯 Benin" },
    { code: "BM", name: "🇧🇲 Bermuda" },
    { code: "BT", name: "🇧🇹 Bhutan" },
    { code: "BO", name: "🇧🇴 Bolivia" },
    { code: "BA", name: "🇧🇦 Bosnia and Herzegovina" },
    { code: "BW", name: "🇧🇼 Botswana" },
    { code: "BR", name: "🇧🇷 Brazil" },
    { code: "BN", name: "🇧🇳 Brunei Darussalam" },
    { code: "BG", name: "🇧🇬 Bulgaria" },
    { code: "BF", name: "🇧🇫 Burkina Faso" },
    { code: "BI", name: "🇧🇮 Burundi" },
    { code: "CV", name: "🇨🇻 Cabo Verde" },
    { code: "KH", name: "🇰🇭 Cambodia" },
    { code: "CM", name: "🇨🇲 Cameroon" },
    { code: "CA", name: "🇨🇦 Canada" },
    { code: "KY", name: "🇰🇾 Cayman Islands" },
    { code: "CF", name: "🇨6 Central African Republic" },
    { code: "TD", name: "🇹🇩 Chad" },
    { code: "CL", name: "🇨🇱 Chile" },
    { code: "CN", name: "🇨🇳 China" },
    { code: "CO", name: "🇨🇴 Colombia" },
    { code: "KM", name: "🇰🇲 Comoros" },
    { code: "CG", name: "🇨🇬 Congo" },
    { code: "CD", name: "🇨🇩 Congo, Democratic Republic of the" },
    { code: "CK", name: "🇨🇰 Cook Islands" },
    { code: "CR", name: "🇨🇷 Costa Rica" },
    { code: "CI", name: "🇨🇮 Côte d'Ivoire" },
    { code: "HR", name: "🇭🇷 Croatia" },
    { code: "CY", name: "🇨🇾 Cyprus" },
    { code: "CZ", name: "🇨🇿 Czech Republic" },
    { code: "DK", name: "🇩🇰 Denmark" },
    { code: "DJ", name: "🇩🇯 Djibouti" },
    { code: "DM", name: "🇩🇲 Dominica" },
    { code: "DO", name: "🇩🇴 Dominican Republic" },
    { code: "EC", name: "🇪🇨 Ecuador" },
    { code: "EG", name: "🇪🇬 Egypt" },
    { code: "SV", name: "🇸🇻 El Salvador" },
    { code: "GQ", name: "🇬🇶 Equatorial Guinea" },
    { code: "ER", name: "🇪🇷 Eritrea" },
    { code: "EE", name: "🇪🇪 Estonia" },
    { code: "SZ", name: "🇸🇿 Eswatini" },
    { code: "ET", name: "🇪🇹 Ethiopia" },
    { code: "FJ", name: "🇫🇯 Fiji" },
    { code: "FI", name: "🇫🇮 Finland" },
    { code: "FR", name: "🇫🇷 France" },
    { code: "GA", name: "🇬🇦 Gabon" },
    { code: "GM", name: "🇬🇲 Gambia" },
    { code: "GE", name: "🇬🇪 Georgia" },
    { code: "DE", name: "🇩🇪 Germany" },
    { code: "GH", name: "🇬🇭 Ghana" },
    { code: "GR", name: "🇬🇷 Greece" },
    { code: "GD", name: "🇬🇩 Grenada" },
    { code: "GU", name: "🇬🇺 Guam" },
    { code: "GT", name: "🇬🇹 Guatemala" },
    { code: "GN", name: "🇬🇳 Guinea" },
    { code: "GW", name: "🇬🇼 Guinea-Bissau" },
    { code: "GY", name: "🇬🇾 Guyana" },
    { code: "HT", name: "🇭🇹 Haiti" },
    { code: "HN", name: "🇭🇳 Honduras" },
    { code: "HK", name: "🇭🇰 Hong Kong" },
    { code: "HU", name: "🇭🇺 Hungary" },
    { code: "IS", name: "🇮🇸 Iceland" },
    { code: "IN", name: "🇮🇳 India" },
    { code: "ID", name: "🇮🇩 Indonesia" },
    { code: "IQ", name: "🇮🇶 Iraq" },
    { code: "IE", name: "🇮🇪 Ireland" },
    { code: "IL", name: "🇮🇱 Israel" },
    { code: "IT", name: "🇮🇹 Italy" },
    { code: "JM", name: "🇯🇲 Jamaica" },
    { code: "JP", name: "🇯🇵 Japan" },
    { code: "JO", name: "🇯🇴 Jordan" },
    { code: "KZ", name: "🇰🇿 Kazakhstan" },
    { code: "KE", name: "🇰🇪 Kenya" },
    { code: "KI", name: "🇰🇮 Kiribati" },
    { code: "KW", name: "🇰🇼 Kuwait" },
    { code: "KG", name: "🇰🇬 Kyrgyzstan" },
    { code: "LA", name: "🇱🇦 Lao People's Democratic Republic" },
    { code: "LV", name: "🇱🇻 Latvia" },
    { code: "LB", name: "🇱🇧 Lebanon" },
    { code: "LS", name: "🇱🇸 Lesotho" },
    { code: "LR", name: "🇱🇷 Liberia" },
    { code: "LY", name: "🇱🇾 Libya" },
    { code: "LI", name: "🇱🇮 Liechtenstein" },
    { code: "LT", name: "🇱🇹 Lithuania" },
    { code: "LU", name: "🇱🇺 Luxembourg" },
    { code: "MG", name: "🇲🇬 Madagascar" },
    { code: "MW", name: "🇲🇼 Malawi" },
    { code: "MY", name: "🇲🇾 Malaysia" },
    { code: "MV", name: "🇲🇻 Maldives" },
    { code: "ML", name: "🇲🇱 Mali" },
    { code: "MT", name: "🇲🇹 Malta" },
    { code: "MH", name: "🇲🇭 Marshall Islands" },
    { code: "MR", name: "🇲🇷 Mauritania" },
    { code: "MU", name: "🇲🇺 Mauritius" },
    { code: "MX", name: "🇲🇽 Mexico" },
    { code: "FM", name: "🇫🇲 Micronesia" },
    { code: "MD", name: "🇲🇩 Moldova" },
    { code: "MC", name: "🇲🇨 Monaco" },
    { code: "MN", name: "🇲🇳 Mongolia" },
    { code: "ME", name: "🇲🇪 Montenegro" },
    { code: "MS", name: "🇲🇸 Montserrat" },
    { code: "MA", name: "🇲🇦 Morocco" },
    { code: "MZ", name: "🇲🇿 Mozambique" },
    { code: "MM", name: "🇲🇲 Myanmar" },
    { code: "NA", name: "🇳🇦 Namibia" },
    { code: "NR", name: "🇳🇷 Nauru" },
    { code: "NP", name: "🇳🇵 Nepal" },
    { code: "NL", name: "🇳🇱 Netherlands" },
    { code: "NZ", name: "🇳🇿 New Zealand" },
    { code: "NI", name: "🇳🇮 Nicaragua" },
    { code: "NE", name: "🇳🇪 Niger" },
    { code: "NG", name: "🇳🇬 Nigeria" },
    { code: "MK", name: "🇲🇰 North Macedonia" },
    { code: "NO", name: "🇳🇴 Norway" },
    { code: "OM", name: "🇴🇲 Oman" },
    { code: "PK", name: "🇵🇰 Pakistan" },
    { code: "PW", name: "🇵🇼 Palau" },
    { code: "PA", name: "🇵🇦 Panama" },
    { code: "PG", name: "🇵🇬 Papua New Guinea" },
    { code: "PY", name: "🇵🇾 Paraguay" },
    { code: "PE", name: "🇵🇪 Peru" },
    { code: "PH", name: "🇵🇭 Philippines" },
    { code: "PL", name: "🇵🇱 Poland" },
    { code: "PT", name: "🇵🇹 Portugal" },
    { code: "PR", name: "🇵🇷 Puerto Rico" },
    { code: "QA", name: "🇶🇦 Qatar" },
    { code: "RO", name: "🇷🇴 Romania" },
    { code: "RW", name: "🇷🇼 Rwanda" },
    { code: "KN", name: "🇰🇳 Saint Kitts and Nevis" },
    { code: "LC", name: "🇱🇨 Saint Lucia" },
    { code: "VC", name: "🇻🇨 Saint Vincent and the Grenadines" },
    { code: "WS", name: "🇼🇸 Samoa" },
    { code: "SM", name: "🇸🇲 San Marino" },
    { code: "ST", name: "🇸🇹 Sao Tome and Principe" },
    { code: "SA", name: "🇸🇦 Saudi Arabia" },
    { code: "SN", name: "🇸🇳 Senegal" },
    { code: "RS", name: "🇷🇸 Serbia" },
    { code: "SC", name: "🇸🇨 Seychelles" },
    { code: "SL", name: "🇸🇱 Sierra Leone" },
    { code: "SG", name: "🇸🇬 Singapore" },
    { code: "SK", name: "🇸🇰 Slovakia" },
    { code: "SI", name: "🇸🇮 Slovenia" },
    { code: "SB", name: "🇸🇧 Solomon Islands" },
    { code: "SO", name: "🇸🇴 Somalia" },
    { code: "ZA", name: "🇿🇦 South Africa" },
    { code: "KR", name: "🇰🇷 South Korea" },
    { code: "ES", name: "🇪🇸 Spain" },
    { code: "LK", name: "🇱🇰 Sri Lanka" },
    { code: "SR", name: "🇸🇷 Suriname" },
    { code: "SE", name: "🇸🇪 Sweden" },
    { code: "CH", name: "🇨🇭 Switzerland" },
    { code: "TW", name: "🇹🇼 Taiwan" },
    { code: "TJ", name: "🇹🇯 Tajikistan" },
    { code: "TZ", name: "🇹🇿 Tanzania" },
    { code: "TH", name: "🇹🇭 Thailand" },
    { code: "TL", name: "🇹🇱 Timor-Leste" },
    { code: "TG", name: "🇹🇬 Togo" },
    { code: "TO", name: "🇹🇴 Tonga" },
    { code: "TT", name: "🇹🇹 Trinidad and Tobago" },
    { code: "TN", name: "🇹🇳 Tunisia" },
    { code: "TR", name: "🇹🇷 Turkey" },
    { code: "TV", name: "🇹🇻 Tuvalu" },
    { code: "UG", name: "🇺🇬 Uganda" },
    { code: "AE", name: "🇦🇪 United Arab Emirates" },
    { code: "GB", name: "🇬🇧 United Kingdom" },
    { code: "US", name: "🇺🇸 United States" },
    { code: "UY", name: "🇺🇾 Uruguay" },
    { code: "UZ", name: "🇺🇿 Uzbekistan" },
    { code: "VU", name: "🇻🇺 Vanuatu" },
    { code: "VN", name: "🇻🇳 Vietnam" },
    { code: "ZM", name: "🇿🇲 Zambia" },
    { code: "ZW", name: "🇿🇼 Zimbabwe" }
];

export const isSupportedCountry = (code: string) => {
    return SUPPORTED_COUNTRIES.some(c => c.code === code);
};

export const US_STATES = [
    { code: 'AL', name: 'Alabama' }, { code: 'AK', name: 'Alaska' }, { code: 'AZ', name: 'Arizona' },
    { code: 'AR', name: 'Arkansas' }, { code: 'CA', name: 'California' }, { code: 'CO', name: 'Colorado' },
    { code: 'CT', name: 'Connecticut' }, { code: 'DE', name: 'Delaware' }, { code: 'DC', name: 'District Of Columbia' },
    { code: 'FL', name: 'Florida' }, { code: 'GA', name: 'Georgia' }, { code: 'HI', name: 'Hawaii' },
    { code: 'ID', name: 'Idaho' }, { code: 'IL', name: 'Illinois' }, { code: 'IN', name: 'Indiana' },
    { code: 'IA', name: 'Iowa' }, { code: 'KS', name: 'Kansas' }, { code: 'KY', name: 'Kentucky' },
    { code: 'LA', name: 'Louisiana' }, { code: 'ME', name: 'Maine' }, { code: 'MD', name: 'Maryland' },
    { code: 'MA', name: 'Massachusetts' }, { code: 'MI', name: 'Michigan' }, { code: 'MN', name: 'Minnesota' },
    { code: 'MS', name: 'Mississippi' }, { code: 'MO', name: 'Missouri' }, { code: 'MT', name: 'Montana' },
    { code: 'NE', name: 'Nebraska' }, { code: 'NV', name: 'Nevada' }, { code: 'NH', name: 'New Hampshire' },
    { code: 'NJ', name: 'New Jersey' }, { code: 'NM', name: 'New Mexico' }, { code: 'NY', name: 'New York' },
    { code: 'NC', name: 'North Carolina' }, { code: 'ND', name: 'North Dakota' }, { code: 'OH', name: 'Ohio' },
    { code: 'OK', name: 'Oklahoma' }, { code: 'OR', name: 'Oregon' }, { code: 'PA', name: 'Pennsylvania' },
    { code: 'RI', name: 'Rhode Island' }, { code: 'SC', name: 'South Carolina' }, { code: 'SD', name: 'South Dakota' },
    { code: 'TN', name: 'Tennessee' }, { code: 'TX', name: 'Texas' }, { code: 'UT', name: 'Utah' },
    { code: 'VT', name: 'Vermont' }, { code: 'VA', name: 'Virginia' }, { code: 'WA', name: 'Washington' },
    { code: 'WV', name: 'West Virginia' }, { code: 'WI', name: 'Wisconsin' }, { code: 'WY', name: 'Wyoming' }
];

export const CA_PROVINCES = [
    { code: 'AB', name: 'Alberta' }, { code: 'BC', name: 'British Columbia' }, { code: 'MB', name: 'Manitoba' },
    { code: 'NB', name: 'New Brunswick' }, { code: 'NL', name: 'Newfoundland and Labrador' }, { code: 'NS', name: 'Nova Scotia' },
    { code: 'NT', name: 'Northwest Territories' }, { code: 'NU', name: 'Nunavut' }, { code: 'ON', name: 'Ontario' },
    { code: 'PE', name: 'Prince Edward Island' }, { code: 'QC', name: 'Quebec' }, { code: 'SK', name: 'Saskatchewan' },
    { code: 'YT', name: 'Yukon' }
];
